### ISSUE TITLE
Datapack validation failed

### ISSUE THREAD

**Issue by CountdownFrom5** [AlexJ314/Whitelist-Minecraft-Biomes#1]
Hello. 
I've been trying to use the Ocean json file for world generation (on Forge 1.19.3) but I can't get it to work. It keeps coming up with a 'datapack validation failed' error. Could you please check whether the problem is with me or the datapack?
Thanks.

**Comment by AlexJ314** [comment]
There's not much I can do with that information, unfortunately.

If you could enable logging before attempting to load the datapack, Minecraft should spit out whatever problems it's having with the datapack into the console which you can then share via pastebin. (obviously remove any information that you don't want publicly available)

Let me know how that goes and I'll see what I can do.

**Comment by CountdownFrom5** [comment]
Sorry for the delay. 

Here is the pastebin link to the game output log: https://paste.gg/p/anonymous/ef30575e6f22434aa8b6a2f0043a798d . The error messege comes up on line 134. 

Thank you for the help. Let me know if I've done the pastebin wrong or if you need more information.

**Comment by AlexJ314** [comment]
My only guess is that either sealevel_world has some variable without a value, or that minecraft 1.19.3 has added some generation settings that my 1.19.2 generation settings don't include. Does it work in 1.19.2 minecraft with or without mods?

**Comment by CountdownFrom5** [comment]
Hello. I've figured out what the problem was. I had deleted the noise_settings folder along with every other folder and so had no sealevel_overworld.json file. Thanks for the help! The pack is working now (forge 1.19.3) and its so good! 

One more question if it's not too much trouble, is there a way to change the maximum height a biome can generate to in the noise file?  I have some mountain like generation and I'm wondering if there's a way to make it so that blocks dont generate above a certain y level so the terrain is more flat (i've lowered sea level to 72). If not then that's fine.

Thanks!

**Comment by AlexJ314** [comment]
I believe there is some logical height you can specify, though I don't know exactly where. It may be the case that `logical_height` refers to the maximum height a chorus fruit is allowed to teleport you, but I encourage you to check the wiki.
